import { useState } from "react";
import { Board } from "./Board";
import type { Action, GameEvent, GameState, PlayerView, RoomState } from "./types";
import { actionToCommand, displayPhase, displayStatus } from "./types";
import { useGameSocket } from "./useSocket";
import type { RoomCredentials } from "./Lobby";

const nameOf = (players: PlayerView[], id: string | null | undefined) => players.find((p) => p.playerId === id)?.displayName ?? "?";
function Group({ label, children }: { label: string; children: React.ReactNode }) { return <div className="action-group"><span className="action-label">{label}：</span><div className="action-buttons">{children}</div></div>; }
function SkillUse({ actions, players, send }: { actions: Action[]; players: PlayerView[]; send: (c: string, p?: Record<string, unknown>) => void }) {
  const modes = actions.filter((a) => a.mode);
  if (modes.length) return <Group label="选择技能效果">{modes.map((a) => <button key={a.mode} onClick={() => send("choose-skill", { use: true, mode: a.mode })}>{a.mode === "harm" ? "强迫目标受伤" : "治疗目标并归还标记"}</button>)}</Group>;
  const targets = actions.filter((a) => a.targetPlayerId);
  if (targets.length) return <Group label="对其使用技能">{targets.map((a) => <button key={a.targetPlayerId} onClick={() => send("choose-skill", { use: true, targetPlayerId: a.targetPlayerId })}>{nameOf(players, a.targetPlayerId)}</button>)}</Group>;
  return <button onClick={() => send("choose-skill", { use: true })}>使用技能</button>;
}
const tokenLabel = (token?: string) => ({ rank: "等级标记", "marker-0": "身份标记 1", "marker-1": "身份标记 2" } as Record<string, string>)[token ?? ""] ?? token ?? "标记";
function CursePicker({ game, send }: { game: GameState; send: (c: string, p?: Record<string, unknown>) => void }) {
  const curses = game.viewer?.cursesToDistribute ?? []; const self = game.viewer?.playerId; const recipients = game.players.filter((p) => p.playerId !== self && !p.captured); const [picks, setPicks] = useState<Record<string, string>>({}); const ready = curses.length > 0 && curses.every((c) => picks[c]);
  return <div className="curse-picker"><p>秘密将诅咒牌交给：</p>{curses.map((id) => <select key={id} value={picks[id] ?? ""} onChange={(e) => setPicks({ ...picks, [id]: e.target.value })}><option value="">请选择</option>{recipients.map((p) => <option key={p.playerId} value={p.playerId}>{p.displayName}</option>)}</select>)}<button disabled={!ready} onClick={() => { send("distribute-curse", { assignments: picks }); setPicks({}); }}>分发诅咒牌</button></div>;
}
function ActionsPanel({ game, hostActions, send, sendHost }: { game: GameState; hostActions: Action[]; send: (c: string, p?: Record<string, unknown>) => void; sendHost: (a: string) => void }) {
  const actions = game.legalActions ?? []; const pass = actions.filter((a) => a.type === "pass-dagger"); const attack = actions.filter((a) => a.type === "attack"); const request = actions.find((a) => a.type === "request-intervention"); const decline = actions.find((a) => a.type === "decline-intervention"); const responders = actions.filter((a) => a.type === "choose-intervention"); const reveals = actions.filter((a) => a.type === "choose-reveal"); const returns = actions.filter((a) => a.type === "choose-return"); const skillUse = actions.filter((a) => a.type === "choose-skill" && a.use); const skillDecline = actions.find((a) => a.type === "choose-skill" && a.use === false); const curse = actions.find((a) => a.type === "distribute-curse"); const locks = hostActions.filter((a) => a.type === "lock" || a.type === "unlock");
  if (!actions.length && !locks.length) return <p className="hint">等待匕首持有者行动。</p>;
  return <div className="actions">{pass.length > 0 && <Group label="将匕首传给">{pass.map((a) => <button key={a.targetPlayerId} onClick={() => { const c = actionToCommand(a); send(c.command, c.payload); }}>{nameOf(game.players, a.targetPlayerId)}</button>)}</Group>}{attack.length > 0 && <Group label="攻击">{attack.map((a) => <button key={a.targetPlayerId} onClick={() => { const c = actionToCommand(a); send(c.command, c.payload); }}>{nameOf(game.players, a.targetPlayerId)}</button>)}</Group>}{request && <button onClick={() => send("request-intervention")}>请求干预</button>}{responders.length > 0 && <Group label="选择干预者">{responders.map((a) => <button key={a.responderPlayerId} onClick={() => { const c = actionToCommand(a); send(c.command, c.payload); }}>{nameOf(game.players, a.responderPlayerId)}</button>)}</Group>}{decline && <button onClick={() => send("decline-intervention")}>拒绝干预</button>}{reveals.length > 0 && <Group label="选择要展示的标记">{reveals.map((a) => <button key={`${a.token}-${a.color ?? ""}`} onClick={() => { const c = actionToCommand(a); send(c.command, c.payload); }}>{tokenLabel(a.token)}{a.color ? `（${a.color === "rose" ? "玫瑰" : "野兽"}）` : ""}</button>)}</Group>}{returns.length > 0 && <Group label="选择归还的标记">{returns.map((a) => <button key={a.token} onClick={() => send("choose-return", { token: a.token })}>{tokenLabel(a.token)}</button>)}</Group>}{skillDecline && <button onClick={() => send("choose-skill", { use: false })}>放弃技能</button>}{skillUse.length > 0 && <SkillUse actions={skillUse} players={game.players} send={send} />}{curse && <CursePicker game={game} send={send} />}{locks.map((a) => <button key={a.type} onClick={() => sendHost(a.type)}>{a.type === "lock" ? "锁定房间" : "解锁房间"}</button>)}</div>;
}
function WaitingRoom({ state, sendHost, spectating }: { state: RoomState; sendHost: (a: string) => void; spectating: boolean }) {
  const players = state.game?.players ?? []; const canStart = players.length >= 6 && players.length <= 12;
  return <div className="waiting"><p>等待玩家加入（{players.length}/12）。分享此房间号，玩家只需房间号和姓名即可加入。</p><ul className="roster">{players.map((p) => <li key={p.playerId}>{p.displayName}{state.connected[p.playerId] ? "" : "（离线）"}</li>)}</ul>{spectating && <p className="hint">你正在旁观。</p>}{state.isHost && <div className="host-panel"><button disabled={!canStart} onClick={() => sendHost("start")}>开始游戏{canStart ? "" : "（需要 6–12 名玩家）"}</button>{state.hostActions.filter((a) => a.type === "lock" || a.type === "unlock").map((a) => <button key={a.type} onClick={() => sendHost(a.type)}>{a.type === "lock" ? "锁定房间" : "解锁房间"}</button>)}</div>}</div>;
}
const eventNames: Record<string, string> = { PlayerJoined: "玩家加入", GameStarted: "游戏开始", DaggerPassed: "匕首传递", AttackDeclared: "宣布攻击", InterventionOpened: "开启干预", InterventionSelected: "选择干预", InterventionDeclined: "拒绝干预", DamageApplied: "造成伤害", ClueRevealed: "展示线索", SkillWindowOpened: "技能窗口开启", SkillUsed: "使用技能", SkillDeclined: "放弃技能", ResourceGranted: "获得资源", PlayerCaptured: "玩家被捕获", GameEnded: "游戏结束", PhaseChanged: "阶段变化" };
function describeEvent(e: GameEvent, players?: PlayerView[]) { const n = (id: unknown) => players?.find((p) => p.playerId === id)?.displayName ?? String(id); const p = e.payload; switch (e.eventType) { case "PlayerJoined": return `${n(p.playerId)} 加入了游戏`; case "GameStarted": return `共 ${p.playerCount} 名玩家`; case "DaggerPassed": return `${n(p.fromPlayerId)} → ${n(p.toPlayerId)}`; case "AttackDeclared": return `${n(p.attackerPlayerId)} 攻击了 ${n(p.targetPlayerId)}`; case "InterventionSelected": return `${n(p.responderPlayerId)} 进行干预`; case "DamageApplied": return `${n(p.targetPlayerId)} 受到 ${p.amount} 点伤害`; case "ClueRevealed": return `${n(p.playerId)} 展示了${String(p.kind) === "rank" ? "等级" : "身份"}线索`; case "SkillUsed": return `${n(p.playerId)} 使用了技能`; case "PlayerCaptured": return `${n(p.playerId)} 被捕获`; case "GameEnded": return "对局结束"; case "PhaseChanged": return `${displayPhase((p.from as { kind: string })?.kind ?? "?")} → ${displayPhase((p.to as { kind: string })?.kind ?? "?")}`; default: return ""; } }
function EventLog({ events, players }: { events: GameEvent[]; players?: PlayerView[] }) { if (!events.length) return null; return <details className="log"><summary>事件日志（{events.length}）</summary><ol>{events.slice(-60).reverse().map((e) => <li key={e.eventId}>{eventNames[e.eventType] ?? e.eventType} {describeEvent(e, players)}</li>)}</ol></details>; }
function Banner({ title, detail, onBack }: { title: string; detail: string; onBack: () => void }) { return <div className="banner"><h2>{title}</h2><p>{detail}</p><button onClick={onBack}>返回大厅</button></div>; }
const errorText = (code: string, _message: string) => ({ "room.locked": "房间已锁定。", "room.already-started": "游戏已经开始。", "game.player-count": "玩家人数必须为 6–12 人。", "player.name-required": "姓名不能为空。" } as Record<string, string>)[code] ?? "操作未完成，请检查当前阶段和操作条件。";
export function GameScreen({ credentials, onLeave }: { credentials: RoomCredentials; onLeave: () => void }) { const { state, events, error, closed, reconnecting, takenOver, send, sendHost } = useGameSocket(credentials.code, credentials.name, credentials.token); if (takenOver) return <Banner title="座位已被接管" detail="同名的新连接已接管此座位，请使用其他姓名重新加入，或等待连接恢复。" onBack={onLeave} />; if (closed && !state && !reconnecting) return <Banner title="连接已断开" detail="房间连接在收到游戏状态前已关闭。" onBack={onLeave} />; if (error && !state) return <Banner title="无法加入房间" detail={errorText(error.code, error.message)} onBack={onLeave} />; if (!state) return <div className="loading">正在连接……</div>; const spectating = state.yourPlayerId === null; const showTable = state.roomStatus === "playing" || state.roomStatus === "ended"; return <div className="room"><header className="room-header"><span>房间 <strong>{state.roomCode}</strong>{state.locked ? " 🔒" : ""} {state.isHost ? "（房主）" : ""}</span><span className="status">{displayStatus(state.roomStatus)}</span>{reconnecting && <span className="hint">正在重新连接……</span>}<button onClick={onLeave}>离开</button></header>{error && <div className="action-error">{errorText(error.code, error.message)}</div>}{showTable && state.game ? <><Board game={state.game} /><ActionsPanel game={state.game} hostActions={state.hostActions} send={send} sendHost={sendHost} /></> : <WaitingRoom state={state} sendHost={sendHost} spectating={spectating} />}<EventLog events={events} players={state.game?.players} /></div>; }
